### ISSUE TITLE
Removal of phpunit from image

### ISSUE THREAD

**Issue by asset-web** [tfirdaus/wp-docklines#9]
Hi

I note in this commit - 253c0a53f91585a7f3f4cd7009f6f0cdc15c5302 you have removed support for phpunit as part of the toolset for this image.  This was a helpful feature. 

Please note the bitbucket pipelines example still references this feature:
https://github.com/tfirdaus/wp-docklines/wiki/Bitbucket-Pipelines

Thanks.

**Comment by tfirdaus** [comment]
@asset-web thanks for the report. I've updated the Wiki to show PHPUnit installation with Composer instead :)
